### PR TITLE
feat: Added Github badge

### PR DESCRIPTION
**Pull request by giri-madhan**
### Scope of change
- Added a GitHub badge that links to the GitHub repository.

### CODE REVIEW

**Comment by stephin007** [comment]
Hey @giri-madhan lets do one more thing. Can you push the name of the app to left and the github symbol to the right?

**Comment by giri-madhan** [comment]
Hi @stephin007, Sorry for the delay. I have updated the alignment of the name and github as requested. Could you provide your comments on this? Thank you.

**Review by stephin007 — APPROVED** [review]
LGTM 🔥

**Comment by stephin007** [comment]
@giri-madhan Looks good! Merging it now. If you want to contribute more, please look into the other issues in the repo.

**Pull request merged**
